COMMA = ','
COLON = ':'
OPENBRACKET = '['
CLOSEBRACKET = ']'
OPENBRACE = '{'
CLOSEBRACE = '}'
QUOTE = '"'
WHITESPACE = [' ', '\t', '\b', '\n', '\r']
JSON_SYNTAX = [COMMA, COLON, OPENBRACKET, CLOSEBRACKET, OPENBRACE, CLOSEBRACE]
FALSE_LEN = len("false")
TRUE_LEN = len("true")
NULL_LEN = len("null")